### GENERAL SETTINGS ###

# Site settings
title: FAB ACADEMY 2017
description: "Fab Academey 2017 -Esteban Martin Gimenez"
analytics: UA-90860442-1
baseurl: "/archives/2017/fablabbcn/students/271"
url: "http://archive.fabacademy.org"
static: "https://nanusefue.github.io/fab2107-static-resource"
# Build settings
markdown: kramdown
permalink: /:categories/:title.html
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/nanusefue
  - title: instagram
    url: https://www.instagram.com/nanusefue/
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
email: nanusefue.at.gmail.dot.com
    

